version: '3'
services:
  dockermirror-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - dockermirror:/var/spool/dockermirror
    ports:
      - 5000:5000/tcp
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
  dockermirror-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockermirror:/var/spool/dockermirror
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  dockermirror:
