version: '3'
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile-api-dev
    volumes:
      - archives:/var/spool/dockermirror
    ports:
      - 5000:5000/tcp
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - archives:/var/spool/dockermirror
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  archives:
