version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - archives:/var/spool/dockermirror
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - archives:/var/spool/dockermirror
    depends_on:
      - redis
  redis:
    image: redis:latest
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80/tcp
    depends_on:
      - api
volumes:
  archives:
    external: true
